var appRouter = function (app) {
  app.get("/", function(req, res) {
  	const quotes=["We have to do one thing at a time.",
"We can’t be fighting ISIS and fighting Assad.",
"We have a country or we don’t have a country.",
"But we can’t be fighting everybody at one time.",
"[Name] is a mess.",
"[Name] is a waste.",
"[Name], in my opinion, nobody cares.",
"[Name] is the weakest person here by far.",
"[Name] is so weak, it’s laughable.",
"[Name] is a big, fat mistake/mess.",
"What a mistake!",
"Wait a minute. Hold it, you dummies!",
"Hey, it’ll never happen.",
"We don’t need a weak person playing this game.",
"Let me talk, quiet.",
"Well, I’ll tell you what. It’ll never happen.",
"We will win and we will win and we will win.",
"It looked like he was looking right at me.",
"I say this every night, every day, every afternoon.",
"Here’s the thing…",
"Let’s get it straight, they don’t want to give it straight.",
"Come on, try getting it out, go ahead.",
"I highly think you should read this book quickly.",
"They’re very dishonest people.",
"We have to be able to express ourselves.",
"That will never happen with me.",
"We’re tired of the nice people.",
"We just spent [monetary amount] dollars on a soccer field.",
"Did you know that?",
"There’s plenty of subject matter right there.",
"I actually gave them a good idea.",
"He would give a sermon. You never wanted to leave.",
"One of the great sleazebags of our time.",
"If I do something wrong, I just try and make it right.",
"All talk, no action.",
"The world is cracking up.",
"More energy tonight, I like that.",
"How can I be tied with this guy? He’s terrible.",
"You can win against China if you’re smart.",
"Arab name, Arab name, Arab name…",
"You’re living in a world of the make-believe.",
"We think it’s good. We think your point is good.",
"He’s sweating like a pig. I’ve never seen a guy sweat like that.",
"This is not exactly a Poker player, folks.",
"That’s what their saying.",
"Who, in my opinion, has not been so hot.",
"I don’t like losers.",
"I don’t think you heard me. You’re having a hard time tonight.",
"I knew before they caught him with the bing-bing-bing.",
"I kill him at golf, I do.",
"I think you can see, I’m having a good time. I really am.",
"I will take care of women. I respect women.",
"He’s rapidly disappearing.",
"I think my strongest asset by far is my temperament.",
"That makes me smart.",
"Nobody has more respect for women than me.",
"I say this is rigged.",
"Such a nasty woman.",
"It's going to be a beautiful thing to watch.",
"I could name, I mean, there are thousands of them.",
"That's called business, by the way.",
"You're telling the enemy everything you want to do.",
"Typical politician. All talk, no action.",
"We are in a big, fat, ugly bubble.",
"I think everybody would agree that she deserves it and nobody feels sorry for her.",
"And in a way, I should be complaining. I'm not even complaining.",
"These are very fine institutions, very fine banks.",
"I have a tremendous income.",
"The reason I say that is not in a braggadocious way.",
"Our airports are like from a third world country.",
"You walk down the street, you get shot.",
"So there's some bad things going on. Some really bad things.",
"No, you're wrong. You're wrong.",
"But, frankly, I look -- I look at that, and I say, isn't that amazing?",
"It also could be somebody sitting on their bed that weighs 400 pounds, OK?",
"The security aspect of cyber is very, very tough.",
"He has computers. He is so good with these computers, it's unbelievable.",
"Well, first I have to say one thing, very important.",
"That line's getting a little bit old, I must say.",
"But they should be paying us, because we are providing tremendous service and we're losing a fortune.",
"And it’s a disgrace, and honestly, you oughta be ashamed of yourself.",
"No, I'm a gentlemen, [Name]. Go ahead.",
"But we have some bad hombres here.",
"No [insult]. No [insult]. You're the [insult].",
"I want you to be very happy. It's very important to me.",
"I tell it like it is.",
"General George Patton and General Douglas MacArthur are spinning in their grave at the stupidity of what we are doing...",
"We have a divided nation because of people like her.",
"Highly thought of and actually very beautifully reviewed by just about everybody.",
"I don't know if it was meant to be a compliment, but it is a great...",
"And when you’re a star, they let you do it. You can do anything.",
"Grab them by the [intimate body part].",
"We've just launched 59 missiles heading to Iraq, and I wanted you to know this.",
"We had the most beautiful piece of chocolate cake that you've ever seen.",
"Korea actually used to be a part of China.",
"Nobody knew [subject] could be so complicated.",
"I like people who weren’t captured.",
"I could stand in the middle of Fifth Avenue and shoot somebody.",
"I felt that I was in the military in the true sense.",
"Bigly"];

  	let data=quotes[Math.floor(Math.random()*quotes.length)];
  
    res.status(200).send(`"${data}" --Donald J. Trump`);
  });
}

module.exports = appRouter;